- replicate/src/fetch.rs
- replicate/src/lib.rs
- replicate/src/types.rs
- replicate/wrangler.toml
- :bug: some types mismatch in API
- :broom: cleanup
- :bug: :label: Unhandled Option types
> Better Replicate API

- .gitignore
- durable-jpeg/src/object.ts
- :tada: :see_no_evil: How to survive without gitignore
- :zap: ability to list all keys from durable object
> durable list

- image/src/index.ts
- image/src/utils/constants.ts
- image/src/utils/cors.ts
- :tada: utils to match origins
- :wrench: main origin is kodadot
- :zap: add allowedOrigin to hono/cors
Close #24
Close kodadot/nft-gallery#4678
> Corsed Image

- .github/workflows/deploy.yml
- image/package-lock.json
- image/package.json
- image/src/index.ts
- image/src/utils/cloudflare-images.ts
> fix: support ipfs full path

- prerender-opengraph/wrangler.toml
- ssr-opengraph/src/index.tsx
- ssr-opengraph/src/template.tsx
- ssr-opengraph/src/types.ts
- ssr-opengraph/src/utils.ts
- ssr-opengraph/wrangler.toml
step to deploy:
1. make sure to deploy `prerender-opengraph` first
2. and then deploy `ssr-opengraph` worker
> feat: ssr-opengraph for collection id

- image-beta/package-lock.json
- image-beta/package.json
- image-beta/src/index.ts
- image-beta/src/utils/cloudflare-images.ts
- ssr-opengraph-beta/README.md
- ssr-opengraph-beta/package-lock.json
- ssr-opengraph-beta/package.json
- ssr-opengraph-beta/src/index.tsx
- ssr-opengraph-beta/src/template.tsx
- ssr-opengraph-beta/src/types.ts
- ssr-opengraph-beta/src/utils.ts
- ssr-opengraph-beta/tsconfig.json
- ssr-opengraph-beta/wrangler.toml
- ssr-opengraph/wrangler.toml
changes:
- match subdomain for ssr-opengraph-beta
- add flush cache key to flush cache for image-beta
> feat: match subdomain for ssr-opengraph

- replicate/Cargo.lock
- replicate/Cargo.toml
- replicate/src/fetch.rs
- replicate/src/lib.rs
- replicate/src/types.rs
- replicate/wrangler.toml
Close #59 
- :arrow_up: @cloudflare worker
- :zap: handle replicate response errs as errs
- :zap: handle predict with correct replicate err
- :label: properly typed replicate input
> Typed Replicate

- ssr-opengraph-beta/package-lock.json
- ssr-opengraph-beta/src/index.tsx
- ssr-opengraph-beta/src/utils.ts
- ssr-opengraph-beta/wrangler.toml
similar to this https://github.com/kodadot/workers/pull/55
> feat: user profiles for beta and canary

- image/src/index.ts
- image/src/utils/cloudflare-images.ts
similar with https://github.com/kodadot/workers/pull/54, but for production
> feat: resize image for production

- ssr-opengraph-beta/src/constant.ts
- ssr-opengraph-beta/src/index.tsx
- ssr-opengraph-beta/src/utils.ts
related issues:
- https://github.com/kodadot/workers/issues/44#issuecomment-1510380772
- https://github.com/kodadot/nft-gallery/issues/5694
tested on:
- collection: https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.preschian.xyz%2Fksm%2Fcollection%2Fbe15890524c6e9b359-TRUSTED%2F
- gallery detail: https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.preschian.xyz%2Fksm%2Fgallery%2F16351286-be15890524c6e9b359-TRUSTED-TRUSTED_CONTRIBUTORS-00004189%2F
- user profile: https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.preschian.xyz%2Fksm%2Fu%2FGsZ1ibHNa3TB5CGCgmFihcD9ARhk3MmMahiokthuUMag1E4%2F
> fix: 404 on trailing slash and update title

- polysearch/.gitignore
- polysearch/README.md
- polysearch/justfile
- polysearch/package-lock.json
- polysearch/package.json
- polysearch/schema.sql
- polysearch/src/index.test.ts
- polysearch/src/index.ts
- polysearch/src/utils/constants.ts
- polysearch/src/utils/cors.ts
- polysearch/src/utils/db.ts
- polysearch/tsconfig.json
- polysearch/wrangler.toml
I wrote the same implementation of `polysearch` I wrote for supabase back then
API is the same and responses should be really fast
- :tada: polysearch init
- :heavy_plus_sign: kysely + d1 adapter
- :wrench: src/index.ts as entry point
- :see_no_evil: local D1
- :robot: justfile at its finest
- :card_file_box: initial SCHEMA
- :label: typemagic
- :tada: KyselySQL
- :tada: v0 works
- GET /search works
- :zap: insert
- :tada: unprotected insert
- :card_file_box: rename schema because naming
- :technologist: return 400 and error
- Close #76
> Very Alpha Search

- replicate/Cargo.lock
- replicate/Cargo.toml
- replicate/src/types.rs
- :arrow_up: deps
- :label: accept webhooks
> Webhooks for replicate

- ssr-opengraph/wrangler.toml
YOLO
- Close #79 
- Close #104
> 🔧 ssr opengraph prerender routes

- ssr-opengraph/src/index.tsx
- ssr-opengraph/wrangler.toml
tested on https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.preschian.xyz%2F
> feat: prerendering for landing page

- ssr-opengraph/package-lock.json
- ssr-opengraph/package.json
tested on https://www.opengraph.xyz/url/https%3A%2F%2Fpreschian.xyz%2Fstmn%2Fgallery%2F19-2
> chore: update kodadot1 packages

- keywise/src/cors.rs
- keywise/src/lib.rs
Don't set cors headers on redirect
> fix: skip cors on redirect

- prerender/wrangler.toml
> fix: drops sub page

- prerender/wrangler.toml
- Related https://github.com/kodadot/nft-gallery/issues/6419
> feat: prerender blog

- image/src/index.ts
- Related https://github.com/kodadot/workers/pull/130
> fix: redirect to cf-ipfs

- image/src/index.ts
http://localhost:8787/ipfs/QmdWuMnTtoA53i23hokJmqSoQBCDRvXrjY4DPTTPppAcEv?original=true
- Related https://github.com/kodadot/nft-gallery/issues/6638
> feat: render original content

- ssr-opengraph/src/template.tsx
Close https://github.com/kodadot/nft-gallery/issues/7001
> fix: HTML lang attribute missing

- scheduled/src/index.ts
- scheduled/wrangler.toml
- :zap: mint city based on cron index
- :wrench: cron times
Ref: 
- https://github.com/kodadot/ops-internal/issues/888
> MultiWaifus

- image/src/utils/cors.ts
- Fix https://github.com/kodadot/workers/issues/156
> fix: add nuxt netlify domain

- image/src/index.ts
> feat: Revalidate image-workers cache. Fixes #38

- polysearch/src/utils/cors.ts
- ref https://github.com/kodadot/nft-gallery/pull/7448#pullrequestreview-1652140401
> fix: cors on nuxt preview

- nft-storage/Cargo.lock
- nft-storage/Cargo.toml
- nft-storage/src/cors.rs
- nft-storage/src/fetch.rs
- nft-storage/src/lib.rs
- nft-storage/src/nftstorage.rs
- nft-storage/wrangler.toml
- :truck: moved corst
- :arrow_up: worker @ 18
- :arrow_up: all other deps
- :zap: posibility to get query param
- :construction: NftStorage Service
- :sparkles: uploading via nftStorage service
- :zap: implement universal response
- :zap: pin json is Using universal response
- :zap: return universal response from pin by url
- :coffin: remove get_key
- :broom: cleanup unused types
> Refactor nft-storage 

- .github/workflows/deploy.yml
- image/package-lock.json
- image/src/index.ts
> fix: return content range

- keywise/Cargo.lock
- keywise/Cargo.toml
- keywise/package-lock.json
- keywise/package.json
- keywise/src/lib.rs
- :arrow_up: wrangler
- :arrow_up: all deps
- :zap: keywise always returns 200 for resolve
Close #143
> KeyWise returns always 200

- ssr-opengraph/src/index.tsx
> chore: rename to ogi

- ogi/components/OgImage/collection.vue
> 🔧 ogi card padding

- ssr-opengraph/src/index.tsx
- ssr-opengraph/src/utils.ts
enable proxy for this changes #199
> feat: gallery detail to ogi

- ogi/components/OgImage/collection.vue
- ogi/components/OgImage/gallery.vue
> 🔧 ogi round price

- price/src/index.ts
- price/src/utils.ts
preflight request looks fine
maybe try to cache it daily? cc @kodadot/internal-dev 
related: https://github.com/kodadot/nft-gallery/issues/8311
> chore: cache daily

- ssr-opengraph/src/utils.ts
> fix: ssr preview

- newsletter/.prettierrc
- newsletter/src/index.ts
- newsletter/src/middleware/validators.ts
- newsletter/src/utils/beehiiv.ts
- newsletter/src/utils/constants.ts
- newsletter/src/utils/cors.ts
- newsletter/src/utils/response.ts
- newsletter/src/utils/types.ts
- newsletter/src/utils/validators.ts
ref 
-
- https://github.com/kodadot/nft-gallery/issues/8575
> feat: Free drops requires activated email

- capture/.prettierrc
- capture/src/index.ts
- capture/src/object.ts
- capture/src/utils/constants.ts
- capture/src/utils/shared.ts
- capture/src/utils/surf.ts
- capture/src/utils/types.ts
> Revert "Revert ":sparkles: New capture""

- newsletter/src/index.ts
- newsletter/src/middleware/validators.ts
- newsletter/src/utils/beehiiv.ts
ref: https://github.com/kodadot/nft-gallery/pull/8668#issuecomment-1865961159
> newsletter: migrate to using subscription id instate of email 

- newsletter/package-lock.json
- newsletter/src/index.ts
- newsletter/src/utils/beehiiv.ts
related https://github.com/kodadot/nft-gallery/issues/8423
> feat: get beehiiv posts

- ogi/components/NftDetail.vue
- ogi/package-lock.json
- ogi/package.json
- ogi/pages/[prefix]/drops/[id]/index.vue
> 🔧 ogi network chainName

- ogi/components/OgImage/collection.vue
> 🔧 ogi network chainName on collection

- ssr-opengraph/src/handlers.ts
- ssr-opengraph/src/index.tsx
- ssr-opengraph/src/template.tsx
- remove unused code
- close #111 
- close #124
> 🔧 ssr-opengraph meta

- ogi/pages/[prefix]/collection/[id]/index.vue
- ogi/utils/handler.ts
Close https://github.com/kodadot/nft-gallery/issues/8814
> fix: item count for collection

- image/src/index.ts
- image/src/routes/ipfs.ts
- image/src/routes/video.ts
- image/src/utils/cloudflare-stream.ts
> feat: cloudflare streams

- party/src/index.ts
- party/src/types/index.ts
issue: https://github.com/kodadot/nft-gallery/issues/9454
> feat: Drop page party kit action status

- ssr-opengraph/public/sandbox.html
- ssr-opengraph/src/index.tsx
- ssr-opengraph/wrangler.toml
fix https://github.com/kodadot/nft-gallery/issues/9526
> feat: serve sandbox html

- ogi/package-lock.json
- ogi/utils/handler.ts
- ogi/utils/types.ts
- fix https://github.com/kodadot/nft-gallery/issues/9839
- fix https://github.com/kodadot/workers/issues/260
test case:
- https://ogi-fix-drops-endpoint.workers-ogi.pages.dev/ahp/drops/break
- https://ogi-fix-drops-endpoint.workers-ogi.pages.dev/ahp/drops/motifs
> fix: drops endpoint

- image/src/routes/metadata.ts
- image/src/routes/type-endpoint.ts
- image/src/utils/cloudflare-images.ts
lefover https://github.com/kodadot/workers/pull/259#discussion_r1535784257
and fix some type missing file
> fix: early return and typo file

- party/src/index.ts
- party/src/types/index.ts
needed for https://github.com/kodadot/nft-gallery/issues/9723
> feat: Partykit mass minting status

- image/src/tests/metadata.test.ts
- ogi/utils/handler.ts
- ssr-opengraph/src/index.tsx
related: 
- https://github.com/kodadot/nft-gallery/issues/9703
- update test regarding https://github.com/kodadot/workers/pull/259
for image, should be automatically changed once [this PR](https://github.com/kodadot/nft-gallery/pull/9869) deployed to production
> chore: change og title on landing page

- image/package-lock.json
- image/package.json
- image/src/tests/metadata.test.ts
- ogi/package-lock.json
- ogi/package.json
- ogi/utils/handler.ts
- ogi/utils/ipfs.ts
- ogi/utils/seo.ts
- price/package-lock.json
- price/package.json
- price/src/utils.ts
- **:arrow_up: deps for OGI**
- **:arrow_up: deps for price worker**
- **:snake: replace bsx with eth**
- **:snake: replace bsx with eth**
- **Fix import in ipfsUrl function**
- **:technologist: naming**
> feat/base for price and OGI

- image/src/utils/cors.ts
- Fix https://github.com/kodadot/workers/issues/285
- Related https://github.com/kodadot/nft-gallery/pull/10183#issuecomment-2090438586
> chore(cors.ts): add new origins for deployment previews and koda.art

- .github/PULL_REQUEST_TEMPLATE.md
I am able to check PRs, but many times i am missing context
Like why do we need this, what does it solve?
How did you solve it ?
> :memo: new minimal PR template

- services/image/src/tests/type-endpoint.test.ts
- services/image/src/utils/ipfs.ts
> chore: add w3s gateway

- shared/utils/index.ts
Update cors rules for kodaart preview pages
> feat(utils): add support for kodaart-production.pages.dev

- ogi/components/NftDetail.vue
- ogi/nuxt.config.ts
- ogi/utils/handler.ts
- services/image/src/routes/type-endpoint.ts
> fix: return cf-images path

- ogi/server/api/evm/[chain]/collection/[id].ts
- ogi/server/api/evm/[chain]/item/[id].ts
- ogi/server/api/evm/item/[id].ts
- ogi/server/utils/evm.ts
Provide api endpoint from onchain data for evm
> feat: evm api for collection & item detail

- services/price/src/utils.ts
> add(price): mantle support 

- ogi/server/api/evm/[chain]/collection/[id].ts
- ogi/server/api/evm/[chain]/item/[id].ts
Add proper cache for this one: https://github.com/kodadot/nft-gallery/pull/10849
> refactor(api): increase SWR cache duration to 5 minutes

- pnpm-lock.yaml
- services/frame/package.json
- services/frame/src/constants.ts
- services/frame/src/index.ts
- services/frame/src/routes/gallery.tsx
- services/frame/src/utils.ts
- **:arrow_up: deps**
- **:coffin: some copypaste garbage**
- **:technologist: new frog definition**
- **:zap: treat collection id as lowercased :)**
- https://github.com/kodadot/nft-gallery/issues/10867
frame results in internal server error
2. _what is the problem?_
problem was that frame was using old uniquery without base prefix, therefore it was failing
2. _how did you solve the problem?_
updated all deps
> :frog: frames

- services/image/src/tests/metadata.test.ts
> fix: image test

- .github/workflows/deploy.yml
> add `ipos` worker to `deploy.yaml`

- services/ipos/src/routes/pinning.ts
2. _what is the problem?_
2. _how did you solve the problem?_
> :zap: fix uploading directories

- shared/utils/index.ts
https://github.com/kodadot/nft-gallery/issues/11326
> fix: allow origin

- pnpm-lock.yaml
- services/image/package.json
- services/image/src/routes/ipfs.ts
- services/image/wrangler.toml
- minor improvement to redirection speed. this will affect some pages such as drops page
- upgrade wrangler version
> feat: improve redirection speed

- shared/utils/index.ts
2. _what is the problem?_
2. _how did you solve the problem?_
> chore: update shared domain
