kodadot/workers

image/src/index.ts, image/src/utils/constants.ts
| before | after |
| --- | --- |
| <img width="1624" alt="Screenshot 2023-01-07 at 20 13 25" src="https://user-images.githubusercontent.com/734428/211153231-e310f7b2-ed01-4e9a-bfe4-47a211677f20.png"> | <img width="1624" alt="Screenshot 2023-01-07 at 20 12 23" src="https://user-images.githubusercontent.com/734428/211153252-f54a7767-6a0c-4e84-b511-e8f90980eebc.png"> |
on already uploaded images to cf-images and hit the fetch cache will be faster (<1s). on a new image still takes > 1s
=> feat: early redirect for image

.github/workflows/deploy.yml
I am trying to learn github actions 🥺 
Ref: 
- https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
- https://github.com/marketplace/actions/deploy-to-cloudflare-workers-with-wrangler
=> :construction_worker: Manual deploy to cf workers

image-beta/package-lock.json, image-beta/src/index.ts, image-beta/src/utils/cloudflare-images.ts
related https://github.com/kodadot/nft-gallery/issues/4872
=> feat: support sub path ipfs

.gitignore, prerender-opengraph/wrangler.toml, ssr-opengraph/README.md, ssr-opengraph/package-lock.json, ssr-opengraph/package.json, ssr-opengraph/src/index.tsx, ssr-opengraph/src/template.tsx, ssr-opengraph/src/types.ts, ssr-opengraph/src/utils.ts, ssr-opengraph/tsconfig.json, ssr-opengraph/wrangler.toml
related https://github.com/kodadot/nft-gallery/issues/5268
the method is quite similar
1. if the request is coming from a non-bot https://github.com/kodadot/workers/pull/41/files#diff-1860af2eaf6e2c14cc185436d808d762199ab1e9ec51fd94afe805d52bf8570eR18 it will continue the request
2. if the request is coming from a crawler (bot) it will fetch data to subsquid and then render static html https://github.com/kodadot/workers/pull/41/files#diff-1860af2eaf6e2c14cc185436d808d762199ab1e9ec51fd94afe805d52bf8570eR54
todo:
step to deploy:
1. after merging this PR, make sure to deploy the `prerender-opengraph` worker first
2. and then deploy `ssr-opengraph`. to avoid routes conflict https://github.com/kodadot/workers/pull/41/files#diff-50d1a6082b03f808cc776ab435488ebf63e81e82829e73e9fc76d094f2d5199aR4 …
=> feat: init ssr-opengraph

ssr-opengraph/src/index.tsx, ssr-opengraph/src/template.tsx, ssr-opengraph/src/utils.ts
not sure why I got different results between localhost and production. only in some items, overall seems ok
| localhost | production |
| --- | --- |
| ![Screenshot 2023-03-25 104123](https://user-images.githubusercontent.com/734428/227690226-e4a50f31-290b-4725-bd38-d0887e0aa539.png) | ![Screenshot 2023-03-25 104105](https://user-images.githubusercontent.com/734428/227690234-c3310152-4aae-492e-9327-96b6be2db5a9.png) |
broken url: 
- https://kodadot.xyz/rmrk/gallery/16818546-64F5867915CADA7250-UNSEEN-RETINA_REALM-0000000000000001
- https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.xyz%2Frmrk%2Fgallery%2F16818546-64F5867915CADA7250-UNSEEN-RETINA_REALM-0000000000000001
meanwhile, it works on my domain 🤔, hhmm:
- https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.preschian.xyz%2Frmrk%2Fgalle …
=> fix: canonical url and add error log

image-beta/src/utils/cloudflare-images.ts
after researching with https://silvia-odwyer.github.io/photon/guide/, still unable to implement that on cf-workers
I found a simple alternative instead by using wsrv.nl. they are using Cloudflare and https://github.com/libvips/libvips. in this PR, we will resize all images to 600
| before | after |
| --- | --- |
| <img width="394" alt="Screenshot 2023-04-02 at 13 35 53" src="https://user-images.githubusercontent.com/734428/229336905-7513d589-96e6-49e3-9630-e6cfb5eb301f.png"> | <img width="389" alt="Screenshot 2023-04-02 at 13 36 58" src="https://user-images.githubusercontent.com/734428/229336912-2aebae20-7762-471f-81ba-d39a6c2b3d33.png"> |
related issue:
- https://github.com/kodadot/nft-gallery/issues/5202
Close kodadot/rubick#189
=> feat: resize image before uploading to cf-images

ssr-opengraph/src/utils.ts
currently in some query there is possibility that nft?.name return null. this PR will check metadata in case nft?.name equal null
=> fix: check if name equal null

nft-storage/Cargo.lock, nft-storage/Cargo.toml, nft-storage/src/lib.rs, nft-storage/wrangler.toml
updates #85
@vikiival do you have any particular mp4 there were issues with? Maybe a larger size. I've tested this and seems to work, maybe it was fixed by simply updating libs :sweat_smile:
=> fix: nft storage can't pin mp4 videos

prerender/wrangler.toml
=> perf: improve seo scores

image/src/index.ts
The problem:
Looks like the gateway cannot correcly process redirects to CF gateways
- :bug: failed to fetch on KodaDot
- :bug: redirect fail on CF_Gateway
Now
This PR
=> Image Worker fails on CF Redirects

image/src/utils/cloudflare-images.ts
Currently, the image worker returns 404 images to Cloudflare images. Because Cloudflare images return 409 status
https://canary.kodadot.xyz/ksm/gallery/13861243-3629a3ff458d113e25-WEAR-AGGRO_T_SHIRT-00000205
=> fix: dont return image on conflict status

image/src/index.ts, image/src/utils/ipfs.ts
While testing this PR https://github.com/kodadot/workers/pull/136, I found that some ipfs cid somehow request to filebase persistent returned 403. it will persistent to redirect it to cf-ipfs
What if we synchronously fetch ipfs?
pros:
- fewer requests to our gateway (reduce cost)
- more precise
cons:
- little bit of increased response time
=> feat: fetch ipfs synchronously

image/src/utils/ipfs.ts
content-type from nftstorage is invalid
this is on cloudflare-ipfs
this is on filebase
this is on infura
let's drop nftstorage on image-workers
=> fix: remove nftstorage because of invalid of content-type

image/src/index.ts
I just noticed that on Chrome, some of the requests were stalled until `12s`. It works fine and loads faster on Firefox.
Hi @kodadot/internal-dev, I am currently deploying this PR to canary/beta env to test the issue. Please report here if you find an error regarding the 301 status code requests to the image worker.
=> fix: redirect status code 301

capture/.vscode/settings.json, capture/package-lock.json, capture/package.json, capture/src/index.ts, capture/src/object.ts, capture/src/utils/constants.ts, capture/src/utils/cors.ts, capture/src/utils/shared.ts, capture/wrangler.toml
https://developers.cloudflare.com/browser-rendering/get-started/browser-rendering-with-do/
This will prolong lifespan of Browser up to One minute + can do response in batches
- :adding: things
- :wrench: vars + DO
- :zap: new features from CF <3
- :sparkles: batch dont fail
- Thanks to the durable object the browser will live min one min if unused -> many users can share session - fast and effective for making screenshots.
- `/screenshot` has still the same api
- `/batch` to capture multiple - returns links to R2
From bottom to top
That is the old capture v0
This but only on new content
This, but content is in R2. 
1:1 to fx-capture
optimize fetching, times on DO <-> R2 <-> others
=> Capture worker v1

image/src/routes/ipfs.ts, image/src/tests/ipfs.test.ts
=> fix: enable cache again

party/src/index.ts, party/src/types/index.ts
https://github.com/kodadot/nft-gallery/pull/9439
=> fix: Partykit handle null connection state 

image/package-lock.json, image/src/routes/ipfs.ts, image/src/utils/cloudflare-images.ts
Fix https://github.com/kodadot/nft-gallery/discussions/10019
Context:
Timeout on filebase:
```
url: https://wsrv.nl/?url=https:%2F%2Fkodadot-ultra.myfilebase.com%2Fipfs%2Fbafybeidkqisbqo3vyejrltlaqeqkxgsvxcuqsmpnw5hczrfhhqrkbcgt3u%2F0.png&w=1400
response: {"status":"error","code":404,"message":"The requested URL timed out."}
```
Changes in this PR:
- switch gateway at the moment to Infura
- remove general cache on ipfs-path
- reorder uploading an image to cf-images
Testcase: this page should load cf-images https://canary.kodadot.xyz/ahp/drops/tilescape instead of original images
=> fix: remove ipfs-path cache

image/src/routes/ipfs.ts, image/src/utils/ipfs.ts
related: https://github.com/kodadot/workers/issues/281
=> feat: add apillon gw

services/image/src/routes/ipfs.ts
- Cache response redirect (change status to 301; Chrome didn't cache 302 response)
=> feat: cache on redirect

services/image/package.json, services/image/src/routes/metadata.ts, services/image/src/utils/ipfs.ts
=> fix: quick fix to filebase

services/image/src/routes/metadata.ts
Quick fix this issue: https://github.com/kodadot/nft-gallery/issues/10347#issuecomment-2135257794 from image workers. There is still some glitch in the UI, but leave it fixed on the nft-gallery side: https://github.com/kodadot/nft-gallery/pull/10349
=> fix: redirecct to fxart metadata

pnpm-lock.yaml, services/image/package.json, services/image/src/routes/ipfs.ts, services/image/src/routes/metadata.ts, services/image/src/utils/cloudflare-images.ts, services/image/src/utils/constants.ts, services/image/src/utils/ipfs.ts, services/image/wrangler.toml
- update packages to the latest version
- early redirect to nftstorage if ipfs gateway timeout. since the redirect is temporary status (302), removed cache header stuff
- remove unused wrangler environment variables
=> fix: early redirect to nftstorage

ogi/components/NftDetail.vue, ogi/package.json, ogi/pages/[prefix]/collection/[id]/index.vue, ogi/pages/[prefix]/drops/[id]/index.vue, ogi/pages/blog/[slug]/index.vue, ogi/pages/index.vue, ogi/utils/handler.ts, pnpm-lock.yaml, services/image/src/routes/metadata.ts, services/image/src/routes/type-endpoint.ts, services/image/src/tests/type-endpoint.test.ts, services/image/src/utils/cloudflare-images.ts, shared/utils/index.ts
Previously it fails render some images. This PR is to force "all" images by using smaller resolution
before: https://ogi.koda.art/ahp/gallery/127-2406146262/__og_image__/og.png
after: https://ogi-fix-opengraph-images.workers-ogi.pages.dev/__og-image__/image/ahp/gallery/127-2406146262/og.png
=> fix: opengraph images

services/image/src/routes/ipfs.ts, services/image/src/tests/ipfs.test.ts, services/image/src/tests/utils/cloudflare-images.test.ts, services/image/src/utils/cloudflare-images.ts
implements
https://developers.cloudflare.com/images/manage-images/enable-flexible-variants/
https://developers.cloudflare.com/images/transform-images/transform-via-url
=> feat(image): cfi flexible variants 

services/image/src/routes/ipfs.ts, services/image/src/tests/type-endpoint.test.ts
Revert: https://github.com/kodadot/workers/issues/311
=> revert: redirect to nftstorage

ogi/components/OgImage/gallery.vue, ogi/package.json, ogi/pages/base/gallery/[id].vue, ogi/utils/seo.ts, pnpm-lock.yaml
add base network to ogi
url: https://ogi-feat--opengraph-for-base.workers-ogi.pages.dev/base/gallery/0xa0e2bca2145b692670125dab579d5075f6a10473-16
opengraph: https://www.opengraph.xyz/url/https%3A%2F%2Fogi-feat--opengraph-for-base.workers-ogi.pages.dev%2Fbase%2Fgallery%2F0xa0e2bca2145b692670125dab579d5075f6a10473-16
=> feat: opengraph for base network

ogi/components/OgImage/base.vue, ogi/components/OgImage/blog.vue, ogi/components/OgImage/collection.vue, ogi/components/OgImage/drops.vue, ogi/components/OgImage/gallery.vue, ogi/utils/constants.ts
https://github.com/kodadot/nft-gallery/issues/10939
2. _what is the problem?_
the logo is old: https://raw.githubusercontent.com/kodadot/kodadot-presskit/main/pre-v4/png/KodalightV4.png
2. _how did you solve the problem?_
upload the new logo and use its URL from github
=> fix: koda logo

ogi/components/OgImage/base-image.vue, ogi/pages/index.vue, ogi/utils/constants.ts, services/image/src/tests/type-endpoint.test.ts
- SEO/opengraph on base route not handled properly
- update test snapshot for image worker
=> fix: opengraph on base route

services/price/wrangler.toml
should not be 0, it works on local
it's missing env vars and its deploying on `price-production.kodadot.workers` not `price.kodadot.workers.dev`
and that is throwing a 500
=> fix(price): internal sever error 

services/ipos/src/routes/pinning.ts, services/ipos/src/utils/format.ts
- ✅ `/pinJson` 
- ✅ `/pinFile` one file , normal size
- ✅ `/pinFile` one file , big size
- ✅ `/pinJson` multiple files
uploading that same file
returns https://ipfs.filebase.io/ipfs/QmfZchkQpaS8wSF3FCEefwmmnEjRwjZSBs3JFnEJWDiDfP
and that matches
=> fix(ipos): invalid `cid`

services/image/src/routes/type-endpoint.ts, services/image/src/utils/cloudflare-images.ts
=> fix: ignore wsrv cache

services/image/src/tests/type-endpoint.test.ts
=> chore: update type endpoint test
